#ifndef BTN_CONFIG_SPRITES_H
#define BTN_CONFIG_SPRITES_H

#ifndef BTN_CFG_SPRITES_MAX_ITEMS
    #define BTN_CFG_SPRITES_MAX_ITEMS 128
#endif

#ifndef BTN_CFG_SPRITES_MAX_SORT_LAYERS
    #define BTN_CFG_SPRITES_MAX_SORT_LAYERS 16
#endif

#endif
