#ifndef BTN_CONFIG_PROFILER_H
#define BTN_CONFIG_PROFILER_H

#ifndef BTN_CFG_PROFILER_ENABLED
    #define BTN_CFG_PROFILER_ENABLED false
#endif

#ifndef BTN_CFG_PROFILER_LOG_ENGINE
    #define BTN_CFG_PROFILER_LOG_ENGINE false
#endif

#ifndef BTN_CFG_PROFILER_TICKS_DIVISOR
    #define BTN_CFG_PROFILER_TICKS_DIVISOR 16
#endif

#ifndef BTN_CFG_PROFILER_MAX_ENTRIES
    #define BTN_CFG_PROFILER_MAX_ENTRIES 64
#endif

#endif
