#ifndef BTN_CONFIG_SPRITE_TILES_H
#define BTN_CONFIG_SPRITE_TILES_H

#ifndef BTN_CFG_SPRITE_TILES_MAX_ITEMS
    #define BTN_CFG_SPRITE_TILES_MAX_ITEMS 128
#endif

#ifndef BTN_CFG_SPRITE_TILES_LOG_ENABLED
    #define BTN_CFG_SPRITE_TILES_LOG_ENABLED false
#endif

#endif
