#ifndef BTN_CONFIG_SPRITE_TEXT_H
#define BTN_CONFIG_SPRITE_TEXT_H

#include "btn_common.h"

#ifndef BTN_CFG_SPRITE_TEXT_MAX_UTF8_CHARACTERS
    #define BTN_CFG_SPRITE_TEXT_MAX_UTF8_CHARACTERS 64
#endif

#endif
