#ifndef BTN_AUDIO_MIXING_RATE_H
#define BTN_AUDIO_MIXING_RATE_H

#include "btn_common.h"

#define BTN_AUDIO_MIXING_RATE_8_KHZ     0

#define BTN_AUDIO_MIXING_RATE_10_KHZ    1

#define BTN_AUDIO_MIXING_RATE_13_KHZ    2

#define BTN_AUDIO_MIXING_RATE_16_KHZ    3

#define BTN_AUDIO_MIXING_RATE_18_KHZ    4

#define BTN_AUDIO_MIXING_RATE_21_KHZ    5

#define BTN_AUDIO_MIXING_RATE_27_KHZ    6

#define BTN_AUDIO_MIXING_RATE_31_KHZ    7

#endif
